import type { Day, Edge, Poi, RoutePath } from "../types";

export function buildGpx(day:Day,pois:Poi[],edges:Edge[]):string{const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e]));const items=[...day.items].sort((a,b)=>a.order-b.order);const points: [number,number][]=[];for(const item of items){const edge=item.fromEdgeId?edgeById.get(item.fromEdgeId):undefined;const path=edge?edgePath(edge):null;if(path?.length){for(const point of path)if(!points.length||points.at(-1)![0]!==point[0]||points.at(-1)![1]!==point[1])points.push(point);}else{const poi=poiById.get(item.poiId);if(poi)points.push([poi.lng,poi.lat]);}}const waypoints=items.map(item=>poiById.get(item.poiId)).filter((p):p is Poi=>!!p).map(p=>`<wpt lat="${p.lat}" lon="${p.lng}"><name>${xml(p.name)}</name></wpt>`).join("");return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Travectory Mobile" xmlns="http://www.topografix.com/GPX/1/1">${waypoints}<trk><name>${xml(day.label||`Day ${day.dayNumber}`)}</name><trkseg>${points.map(p=>`<trkpt lat="${p[1]}" lon="${p[0]}"/>`).join("")}</trkseg></trk></gpx>`;}

export function buildRoadbookHtml(name:string,description:string,days:Day[],pois:Poi[],edges:Edge[]):string{const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e]));const overview=svgOverview(edges,920,390);const cards=[...days].sort((a,b)=>a.dayNumber-b.dayNumber).map(day=>{const items=[...day.items].sort((a,b)=>a.order-b.order);const totals=dayTotals(day,edgeById);return `<section><header><div><small>DAY ${day.dayNumber}</small><h2>${html(day.label||`第 ${day.dayNumber} 天`)}</h2></div><b>${distance(totals.distance)} · ${duration(totals.duration)}${totals.tolls?` · ¥${Math.round(totals.tolls)}`:""}</b></header>${items.map((item,index)=>{const poi=poiById.get(item.poiId),metric=item.fromEdgeId?edgeMetric(edgeById.get(item.fromEdgeId)):null;return `<article><i>${index+1}</i><div><strong>${html(poi?.name||"未命名地点")}</strong><span>${metric?`${distance(metric.distance)} · ${duration(metric.duration)}`:html(poi?.address||"日程起点")}</span></div></article>`;}).join("")}${day.notesContent?`<p>${html(day.notesContent)}</p>`:""}</section>`;}).join("");return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${html(name)}</title><style>*{box-sizing:border-box}body{margin:0;background:#eef2f8;color:#172033;font-family:system-ui,"Microsoft YaHei",sans-serif}.hero{padding:34px 5vw;color:white;background:linear-gradient(135deg,#2549bd,#5376e5)}.hero h1{margin:6px 0;font-size:30px}.hero p{margin:0;opacity:.8}.map{margin:22px auto;max-width:980px;padding:16px;border-radius:22px;background:white;box-shadow:0 8px 28px #23365b18}.map h3{margin:0 0 12px}main{max-width:980px;margin:auto;padding:0 14px 36px}section{margin:15px 0;padding:20px;border-radius:20px;background:white;box-shadow:0 7px 24px #23365b10}section header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e8ebf2;padding-bottom:13px}h2{margin:3px 0 0}small,article span{color:#7c879b}article{display:grid;grid-template-columns:34px 1fr;align-items:center;gap:10px;padding:13px 0;border-bottom:1px solid #eef0f5}article i{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;color:white;background:#3157d5;font-style:normal}article strong,article span{display:block}article span{margin-top:4px;font-size:12px}section p{padding:12px;border-radius:12px;background:#f5f7fb;color:#657086}@media(max-width:600px){section header{align-items:flex-start;gap:8px;flex-direction:column}.hero h1{font-size:24px}}</style></head><body><div class="hero"><small>TRAVECTORY MOBILE</small><h1>${html(name)}</h1><p>${html(description||`${days.length} 天 · ${pois.length} 个地点 · ${edges.length} 条路线`)}</p></div><div class="map"><h3>全程路线总览</h3>${overview}</div><main>${cards}</main></body></html>`;}

export async function buildRoadbookPng(name:string,days:Day[],pois:Poi[],edges:Edge[]):Promise<Blob>{const width=1080,padding=60,overviewH=390;const sorted=[...days].sort((a,b)=>a.dayNumber-b.dayNumber),height=padding+125+overviewH+50+sorted.reduce((sum,d)=>sum+125+Math.max(1,d.items.length)*76+34,0);const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("浏览器不支持长图生成");ctx.fillStyle="#eef2f8";ctx.fillRect(0,0,width,height);ctx.fillStyle="#3157d5";ctx.fillRect(0,0,width,150);ctx.fillStyle="white";ctx.font="700 44px system-ui, Microsoft YaHei";ctx.fillText(name,padding,72);ctx.font="22px system-ui, Microsoft YaHei";ctx.globalAlpha=.8;ctx.fillText(`${days.length} 天 · ${pois.length} 个地点 · ${edges.length} 条路线`,padding,112);ctx.globalAlpha=1;let y=175;roundRect(ctx,padding,y,width-padding*2,overviewH,24,"#ffffff");ctx.fillStyle="#172033";ctx.font="700 25px system-ui, Microsoft YaHei";ctx.fillText("全程路线总览",padding+25,y+42);drawOverview(ctx,edges,padding+25,y+65,width-padding*2-50,overviewH-90);y+=overviewH+25;const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e]));for(const day of sorted){const items=[...day.items].sort((a,b)=>a.order-b.order),cardH=100+Math.max(1,items.length)*76;roundRect(ctx,padding,y,width-padding*2,cardH,24,"#ffffff");ctx.fillStyle="#3157d5";ctx.font="700 20px system-ui";ctx.fillText(`DAY ${day.dayNumber}`,padding+25,y+36);ctx.fillStyle="#172033";ctx.font="700 30px system-ui, Microsoft YaHei";ctx.fillText(day.label||`第 ${day.dayNumber} 天`,padding+25,y+72);const totals=dayTotals(day,edgeById);ctx.textAlign="right";ctx.font="600 19px system-ui, Microsoft YaHei";ctx.fillStyle="#657086";ctx.fillText(`${distance(totals.distance)} · ${duration(totals.duration)}${totals.tolls?` · ¥${Math.round(totals.tolls)}`:""}`,width-padding-25,y+58);ctx.textAlign="left";let iy=y+105;for(let index=0;index<items.length;index++){const item=items[index],poi=poiById.get(item.poiId),metric=item.fromEdgeId?edgeMetric(edgeById.get(item.fromEdgeId)):null;ctx.beginPath();ctx.fillStyle="#3157d5";ctx.arc(padding+42,iy-8,17,0,Math.PI*2);ctx.fill();ctx.fillStyle="white";ctx.font="700 15px system-ui";ctx.textAlign="center";ctx.fillText(String(index+1),padding+42,iy-3);ctx.textAlign="left";ctx.fillStyle="#172033";ctx.font="600 22px system-ui, Microsoft YaHei";ctx.fillText(poi?.name||"未命名地点",padding+76,iy-7);ctx.fillStyle="#7c879b";ctx.font="17px system-ui, Microsoft YaHei";ctx.fillText(metric?`${distance(metric.distance)} · ${duration(metric.duration)}`:poi?.address||"日程起点",padding+76,iy+20);iy+=76;}y+=cardH+24;}return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("长图生成失败")),"image/png"));}

function svgOverview(edges:Edge[],width:number,height:number):string{const paths=allPaths(edges),box=bounds(paths);if(!box)return `<svg viewBox="0 0 ${width} ${height}" style="width:100%;background:#eef2f6;border-radius:16px"><text x="50%" y="50%" text-anchor="middle" fill="#8993a5">暂无路线</text></svg>`;return `<svg viewBox="0 0 ${width} ${height}" style="width:100%;background:#eef2f6;border-radius:16px">${paths.map((path,index)=>`<polyline points="${path.map(p=>project(p,box,width,height,28).join(",")).join(" ")}" fill="none" stroke="${colors[index%colors.length]}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>`).join("")}</svg>`;}
function drawOverview(ctx:CanvasRenderingContext2D,edges:Edge[],x:number,y:number,w:number,h:number){ctx.fillStyle="#eef2f6";ctx.fillRect(x,y,w,h);const paths=allPaths(edges),box=bounds(paths);if(!box)return;paths.forEach((path,index)=>{ctx.beginPath();path.forEach((p,i)=>{const [px,py]=project(p,box,w,h,24);i?ctx.lineTo(x+px,y+py):ctx.moveTo(x+px,y+py);});ctx.strokeStyle=colors[index%colors.length];ctx.lineWidth=5;ctx.lineJoin="round";ctx.lineCap="round";ctx.stroke();});}
const colors=["#3157d5","#e05266","#14a37f","#e59a28","#805ad5","#0891b2"];
function allPaths(edges:Edge[]){return edges.map(edgePath).filter((p):p is [number,number][]=>!!p&&p.length>1);}
function bounds(paths:[number,number][][]){const points=paths.flat();if(!points.length)return null;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return {minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}
function project(p:[number,number],b:NonNullable<ReturnType<typeof bounds>>,w:number,h:number,pad:number):[number,number]{const dx=Math.max(.000001,b.maxX-b.minX),dy=Math.max(.000001,b.maxY-b.minY),scale=Math.min((w-pad*2)/dx,(h-pad*2)/dy);return [pad+(p[0]-b.minX)*scale,h-pad-(p[1]-b.minY)*scale];}
function edgePath(edge:Edge):[number,number][]|null{if(edge.customRoute?.polyline?.length)return edge.customRoute.polyline;const routes=edge.drivingRoutes?.length?edge.drivingRoutes:edge.cyclingRoutes?.length?edge.cyclingRoutes:edge.walkingRoutes||[];return routes[edge.selectedRouteIndex]?.polyline||routes[0]?.polyline||null;}
function edgeMetric(edge?:Edge){if(!edge)return null;if(edge.customRoute)return edge.customRoute;const routes:RoutePath[]=edge.drivingRoutes?.length?edge.drivingRoutes:edge.cyclingRoutes?.length?edge.cyclingRoutes:edge.walkingRoutes||[];return routes[edge.selectedRouteIndex]||routes[0]||null;}
function dayTotals(day:Day,edges:Map<string,Edge>){return day.items.reduce((sum,item)=>{const m=item.fromEdgeId?edgeMetric(edges.get(item.fromEdgeId)):null;if(m){sum.distance+=m.distance||0;sum.duration+=m.duration||0;sum.tolls+=("tolls" in m?Number(m.tolls):0)||0;}return sum;},{distance:0,duration:0,tolls:0});}
function distance(m:number){return m>=1000?`${(m/1000).toFixed(m>=100000?0:1)} km`:`${Math.round(m)} m`;}
function duration(s:number){const minutes=Math.round(s/60),hours=Math.floor(minutes/60);return hours?`${hours}小时${minutes%60?`${minutes%60}分钟`:""}`:`${minutes}分钟`;}
function html(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));}function xml(v:string){return html(v);}
function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,color:string){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=color;ctx.fill();}
