import type { Day, Edge, Poi, RoutePath } from "../types";

const DAY_COLORS = ["#2563eb", "#f97316", "#10b981", "#8b5cf6", "#e11d48", "#0891b2"];
const TRANSPORT_LABELS: Record<string,string> = { driving:"驾车", walking:"步行", cycling:"骑行", transit:"公交", flight:"飞机", train:"火车", other:"其他" };
const WEB_KEY = process.env.NEXT_PUBLIC_AMAP_WEB_KEY || "";

export function buildGpx(day:Day,pois:Poi[],edges:Edge[]):string{const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e]));const items=[...day.items].sort((a,b)=>a.order-b.order);const points:[number,number][]=[];for(const item of items){const edge=item.fromEdgeId?edgeById.get(item.fromEdgeId):undefined;const path=edge?edgePath(edge):null;if(path?.length){for(const point of path)if(!points.length||points.at(-1)![0]!==point[0]||points.at(-1)![1]!==point[1])points.push(point);}else{const poi=poiById.get(item.poiId);if(poi)points.push([poi.lng,poi.lat]);}}const waypoints=items.map(item=>poiById.get(item.poiId)).filter((p):p is Poi=>!!p).map(p=>`<wpt lat="${p.lat}" lon="${p.lng}"><name>${xml(p.name)}</name></wpt>`).join("");return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Travectory Mobile" xmlns="http://www.topografix.com/GPX/1/1">${waypoints}<trk><name>${xml(day.label||`Day ${day.dayNumber}`)}</name><trkseg>${points.map(p=>`<trkpt lat="${p[1]}" lon="${p[0]}"/>`).join("")}</trkseg></trk></gpx>`;}

export function buildRoadbookHtml(name:string,description:string,days:Day[],pois:Poi[],edges:Edge[]):string{const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e]));const overview=svgOverview(days,pois,edges,920,390);const cards=[...days].sort((a,b)=>a.dayNumber-b.dayNumber).map((day,dayIndex)=>{const color=DAY_COLORS[dayIndex%DAY_COLORS.length],items=[...day.items].sort((a,b)=>a.order-b.order),totals=dayTotals(day,edgeById);return `<section style="border-left:6px solid ${color}"><header><div><small style="color:${color}">DAY ${day.dayNumber}</small><h2>${html(exportDayLabel(day))}</h2></div><b>${distance(totals.distance)} · ${duration(totals.duration)}${totals.tolls?` · ¥${formatTolls(totals.tolls)}`:""}</b></header>${items.map((item,index)=>{const poi=poiById.get(item.poiId),metric=item.fromEdgeId?edgeMetric(edgeById.get(item.fromEdgeId)):null;return `<article><i style="background:${color}">${index+1}</i><div><strong>${html(poi?.name||"未命名地点")}</strong><span>${metric?`${distance(metric.distance)} · ${duration(metric.duration)}`:html(poi?.address||"日程起点")}</span></div></article>`;}).join("")}${day.notesContent?`<p>${html(day.notesContent)}</p>`:""}</section>`;}).join("");return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${html(name)}</title><style>*{box-sizing:border-box}body{margin:0;background:#eef2f8;color:#172033;font-family:system-ui,"Microsoft YaHei",sans-serif}.hero{padding:34px 5vw;color:white;background:linear-gradient(135deg,#2549bd,#5376e5)}.hero h1{margin:6px 0;font-size:30px}.hero p{margin:0;opacity:.8}.map{margin:22px auto;max-width:980px;padding:16px;border-radius:22px;background:white}.map h3{margin:0 0 12px}main{max-width:980px;margin:auto;padding:0 14px 36px}section{margin:15px 0;padding:20px;border-radius:20px;background:white}section header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e8ebf2;padding-bottom:13px}h2{margin:3px 0 0}small,article span{color:#7c879b}article{display:grid;grid-template-columns:34px 1fr;align-items:center;gap:10px;padding:13px 0;border-bottom:1px solid #eef0f5}article i{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;color:white;font-style:normal}article strong,article span{display:block}article span{margin-top:4px;font-size:12px}</style></head><body><div class="hero"><small>TRAVECTORY MOBILE</small><h1>${html(name)}</h1><p>${html(description||`${days.length} 天 · ${pois.length} 个地点 · ${edges.length} 条路线`)}</p></div><div class="map"><h3>按日程路线总览</h3>${overview}</div><main>${cards}</main></body></html>`;}

export async function buildRoadbookPng(name:string,description:string,days:Day[],pois:Poi[],edges:Edge[]):Promise<Blob>{
  const width=1080,side=48,mapX=72,mapY=500,mapW=936,mapH=520;
  const sorted=[...days].sort((a,b)=>a.dayNumber-b.dayNumber),dayHeights=sorted.map(day=>112+Math.max(day.items.length,1)*100+32),contentH=dayHeights.reduce((sum,h)=>sum+h+28,0),height=Math.max(1578,1108+contentH+100);
  const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("浏览器不支持长图生成");
  const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e]));let totalDistance=0,totalDuration=0;sorted.forEach(day=>day.items.forEach(item=>{const metric=item.fromEdgeId?edgeMetric(edgeById.get(item.fromEdgeId)):null;if(metric){totalDistance+=metric.distance||0;totalDuration+=metric.duration||0;}}));
  ctx.fillStyle="#f3f6fb";ctx.fillRect(0,0,width,height);ctx.fillStyle="#3157d5";ctx.fillRect(0,0,width,300);ctx.globalAlpha=.07;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(930,40,210,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.05;ctx.beginPath();ctx.arc(90,290,150,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
  drawText(ctx,side,76,"TRAVECTORY 旅行路书",24,"#dbeafe",600);drawText(ctx,side,145,truncate(name||"未命名路书",24),52,"#fff",700);drawText(ctx,side,194,truncate(description||"把远方，安排成清晰的每一天",42),24,"#dbeafe");drawText(ctx,side,256,`${sorted.length} 天行程`,27,"#fff",600);drawText(ctx,255,256,`${pois.length} 个地点`,27,"#fff",600);drawText(ctx,465,256,chinaDate(),24,"#dbeafe");
  roundRect(ctx,side,326,width-side*2,82,20,"#fff");drawText(ctx,82,360,"路线总览",18,"#64748b",600);drawText(ctx,82,390,`总里程 ${distance(totalDistance)}`,24,"#0f172a",700);drawText(ctx,415,390,`交通耗时 ${duration(totalDuration)}`,24,"#0f172a",700);drawText(ctx,815,390,`${edges.length} 条路线`,24,"#0f172a",700);
  roundRect(ctx,side,436,width-side*2,650,24,"#fff");drawText(ctx,76,480,"按日程路线总览",27,"#0f172a",700);drawText(ctx,805,478,"每日路线以不同颜色标识",17,"#64748b");await drawOverviewMap(ctx,sorted,pois,edges,mapX,mapY,mapW,mapH);
  let dayY=1114;sorted.forEach((day,dayIndex)=>{const color=DAY_COLORS[dayIndex%DAY_COLORS.length],items=[...day.items].sort((a,b)=>a.order-b.order),cardH=dayHeights[dayIndex],totals=dayTotals(day,edgeById);roundRect(ctx,side,dayY,width-side*2,cardH,24,"#fff");roundRect(ctx,side,dayY,10,cardH,5,color);drawText(ctx,82,dayY+48,`DAY ${day.dayNumber}`,20,color,700);drawText(ctx,200,dayY+49,truncate(exportDayLabel(day),28),30,"#0f172a",700);drawText(ctx,82,dayY+84,day.date||`${items.length} 个行程地点`,19,"#64748b");roundRect(ctx,468,dayY+61,532,40,12,"#f5f7fb");drawText(ctx,486,dayY+87,`行驶里程 ${distance(totals.distance)}`,17,"#475569",600);drawText(ctx,674,dayY+87,`行驶时长 ${duration(totals.duration)}`,17,"#475569",600);drawText(ctx,884,dayY+87,`总过路费 ¥${formatTolls(totals.tolls)}`,17,"#475569",600);
    if(!items.length)drawText(ctx,82,dayY+148,"当天尚未安排行程",23,"#94a3b8");items.forEach((item,itemIndex)=>{const poi=poiById.get(item.poiId),rowY=dayY+112+itemIndex*100;if(itemIndex<items.length-1){ctx.save();ctx.setLineDash([6,7]);ctx.strokeStyle=color;ctx.globalAlpha=.45;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(108,rowY+36);ctx.lineTo(108,rowY+106);ctx.stroke();ctx.restore();}ctx.fillStyle=color;ctx.beginPath();ctx.arc(108,rowY+28,25,0,Math.PI*2);ctx.fill();drawText(ctx,itemIndex+1>=10?94:100,rowY+37,String(itemIndex+1),22,"#fff",700);drawText(ctx,154,rowY+25,truncate(poi?.name||"未命名地点",30),27,"#172033",700);drawText(ctx,154,rowY+57,truncate(poi?.address||"",48),18,"#64748b");if(itemIndex>0&&item.fromEdgeId){const edge=edgeById.get(item.fromEdgeId),metric=edgeMetric(edge);if(edge&&metric)drawText(ctx,690,rowY+35,`${TRANSPORT_LABELS[edge.transportMode]||edge.transportMode} · ${distance(metric.distance)} · ${duration(metric.duration)}`,18,color,600);}});dayY+=cardH+28;});
  drawText(ctx,side,height-46,`由 Travectory 生成 · ${chinaDate()}`,18,"#94a3b8");drawText(ctx,width-270,height-46,"愿每一程都有好风景",18,"#94a3b8");return canvasBlob(canvas);
}

async function drawOverviewMap(ctx:CanvasRenderingContext2D,days:Day[],pois:Poi[],edges:Edge[],x:number,y:number,w:number,h:number){const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e])),segments:{dayIndex:number;points:[number,number][]}[]=[],markers:{dayIndex:number;itemIndex:number;point:[number,number]}[]=[];days.forEach((day,dayIndex)=>{const items=[...day.items].sort((a,b)=>a.order-b.order);items.forEach((item,itemIndex)=>{const poi=poiById.get(item.poiId);if(poi)markers.push({dayIndex,itemIndex,point:[poi.lng,poi.lat]});if(!itemIndex)return;const previous=poiById.get(items[itemIndex-1].poiId),edge=item.fromEdgeId?edgeById.get(item.fromEdgeId):undefined,path=edge?edgePath(edge):null;if(path&&path.length>=2)segments.push({dayIndex,points:path});else if(previous&&poi)segments.push({dayIndex,points:[[previous.lng,previous.lat],[poi.lng,poi.lat]]});});});const all=[...segments.flatMap(s=>s.points),...markers.map(m=>m.point)];roundRect(ctx,x,y,w,h,16,"#e8edf3");if(!all.length){drawText(ctx,x+w/2-120,y+h/2,"暂无可展示的地图路线",24,"#94a3b8",600);return;}const zero=all.map(p=>mercator(p[0],p[1],0)),minX=Math.min(...zero.map(p=>p[0])),maxX=Math.max(...zero.map(p=>p[0])),minY=Math.min(...zero.map(p=>p[1])),maxY=Math.max(...zero.map(p=>p[1])),centerZero:[number,number]=[(minX+maxX)/2,(minY+maxY)/2],centerLngLat=inverseMercator(centerZero[0],centerZero[1]),scaleX=(w-56)/Math.max(maxX-minX,.000001),scaleY=(h-56)/Math.max(maxY-minY,.000001),zoom=Math.max(1,Math.min(17,Math.floor(Math.log2(Math.min(scaleX,scaleY))))),staticZoom=Math.max(1,zoom-1),center=mercator(centerLngLat[0],centerLngLat[1],staticZoom),projectedW=Math.max((maxX-minX)*2**staticZoom,1),projectedH=Math.max((maxY-minY)*2**staticZoom,1),visualScale=Math.max(1,Math.min((w-56)/projectedW,(h-56)/projectedH));
  ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,16);ctx.clip();if(WEB_KEY){try{const url=new URL("https://restapi.amap.com/v3/staticmap");url.searchParams.set("key",WEB_KEY);url.searchParams.set("location",`${centerLngLat[0].toFixed(6)},${centerLngLat[1].toFixed(6)}`);url.searchParams.set("zoom",String(staticZoom));url.searchParams.set("size",`${w}*${h}`);url.searchParams.set("scale","1");const image=await loadImage(url.toString());const cropW=w/visualScale,cropH=h/visualScale;ctx.drawImage(image,(w-cropW)/2,(h-cropH)/2,cropW,cropH,x,y,w,h);}catch{/* 保留中性底图并继续绘制路线 */}}
  const toPoint=(point:[number,number]):[number,number]=>{const p=mercator(point[0],point[1],staticZoom);return[x+w/2+(p[0]-center[0])*visualScale,y+h/2+(p[1]-center[1])*visualScale];};segments.forEach(segment=>{const points=segment.points.map(toPoint);ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();points.forEach((p,index)=>index?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle="rgba(255,255,255,.85)";ctx.lineWidth=12;ctx.stroke();ctx.strokeStyle=DAY_COLORS[segment.dayIndex%DAY_COLORS.length];ctx.lineWidth=7;ctx.stroke();});markers.forEach(marker=>{const [px,py]=toPoint(marker.point),color=DAY_COLORS[marker.dayIndex%DAY_COLORS.length];if(marker.itemIndex===0){ctx.fillStyle="#fff";ctx.strokeStyle=color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(px,py,16,0,Math.PI*2);ctx.fill();ctx.stroke();drawText(ctx,px-10,py+5,`D${marker.dayIndex+1}`,12,color,700);}else{ctx.fillStyle=color;ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(px,py,7,0,Math.PI*2);ctx.fill();ctx.stroke();}});ctx.restore();}

function svgOverview(days:Day[],pois:Poi[],edges:Edge[],width:number,height:number):string{const poiById=new Map(pois.map(p=>[p.id,p])),edgeById=new Map(edges.map(e=>[e.id,e])),paths:{dayIndex:number;points:[number,number][]}[]=[];days.forEach((day,dayIndex)=>[...day.items].sort((a,b)=>a.order-b.order).forEach((item,index,items)=>{if(!index)return;const edge=item.fromEdgeId?edgeById.get(item.fromEdgeId):undefined,p=edge?edgePath(edge):null,from=poiById.get(items[index-1].poiId),to=poiById.get(item.poiId);if(p?.length)paths.push({dayIndex,points:p});else if(from&&to)paths.push({dayIndex,points:[[from.lng,from.lat],[to.lng,to.lat]]});}));const box=bounds(paths.map(p=>p.points));if(!box)return `<svg viewBox="0 0 ${width} ${height}" style="width:100%;background:#eef2f6;border-radius:16px"><text x="50%" y="50%" text-anchor="middle" fill="#8993a5">暂无路线</text></svg>`;return `<svg viewBox="0 0 ${width} ${height}" style="width:100%;background:#eef2f6;border-radius:16px">${paths.map(path=>`<polyline points="${path.points.map(p=>project(p,box,width,height,28).join(",")).join(" ")}" fill="none" stroke="${DAY_COLORS[path.dayIndex%DAY_COLORS.length]}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>`).join("")}</svg>`;}
function edgePath(edge:Edge):[number,number][]|null{if(edge.customRoute?.polyline?.length)return edge.customRoute.polyline;const routes=edge.drivingRoutes?.length?edge.drivingRoutes:edge.cyclingRoutes?.length?edge.cyclingRoutes:edge.walkingRoutes||[];return routes[edge.selectedRouteIndex]?.polyline||routes[0]?.polyline||null;}
function edgeMetric(edge?:Edge){if(!edge)return null;if(edge.customRoute)return edge.customRoute;const routes:RoutePath[]=edge.drivingRoutes?.length?edge.drivingRoutes:edge.cyclingRoutes?.length?edge.cyclingRoutes:edge.walkingRoutes||[];return routes[edge.selectedRouteIndex]||routes[0]||null;}
function dayTotals(day:Day,edges:Map<string,Edge>){return day.items.reduce((sum,item)=>{const m=item.fromEdgeId?edgeMetric(edges.get(item.fromEdgeId)):null;if(m){sum.distance+=m.distance||0;sum.duration+=m.duration||0;sum.tolls+=("tolls" in m?Number(m.tolls):0)||0;}return sum;},{distance:0,duration:0,tolls:0});}
function mercator(lng:number,lat:number,zoom:number):[number,number]{const size=256*2**zoom,limited=Math.max(-85.05112878,Math.min(85.05112878,lat)),sin=Math.sin(limited*Math.PI/180);return[((lng+180)/360)*size,(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*size];}function inverseMercator(x:number,y:number):[number,number]{const lng=x/256*360-180,n=Math.PI-2*Math.PI*y/256;return[lng,180/Math.PI*Math.atan(Math.sinh(n))];}
function bounds(paths:[number,number][][]){const points=paths.flat();if(!points.length)return null;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}function project(p:[number,number],b:NonNullable<ReturnType<typeof bounds>>,w:number,h:number,pad:number):[number,number]{const dx=Math.max(.000001,b.maxX-b.minX),dy=Math.max(.000001,b.maxY-b.minY),scale=Math.min((w-pad*2)/dx,(h-pad*2)/dy);return[pad+(p[0]-b.minX)*scale,h-pad-(p[1]-b.minY)*scale];}
function exportDayLabel(day:Day){const label=day.label?.trim()||"",generated=!label||/^day\s*\d+$/i.test(label)||/^第\s*(?:\d+|[零〇一二两三四五六七八九十百千万]+)\s*天$/.test(label);return generated?`第${toChineseNumber(day.dayNumber)}天`:label;}function toChineseNumber(value:number){const n=Math.max(0,Math.trunc(value));if(n===0)return"零";if(n>=10000)return String(n);const digits=["零","一","二","三","四","五","六","七","八","九"],units=["","十","百","千"],chars:string[]=[];let zero=false;for(let pos=3;pos>=0;pos--){const d=Math.floor(n/10**pos)%10;if(!d){if(chars.length)zero=true;continue;}if(zero)chars.push("零");if(!(d===1&&pos===1&&!chars.length))chars.push(digits[d]);chars.push(units[pos]);zero=false;}return chars.join("");}
function drawText(ctx:CanvasRenderingContext2D,x:number,y:number,value:string,size:number,color:string,weight=400){ctx.fillStyle=color;ctx.font=`${weight} ${size}px system-ui, Microsoft YaHei, sans-serif`;ctx.textAlign="left";ctx.fillText(value,x,y);}function truncate(value:string,max:number){const chars=Array.from(value.trim());return chars.length>max?`${chars.slice(0,max-1).join("")}…`:chars.join("");}function chinaDate(){return new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",year:"numeric",month:"long",day:"numeric"}).format(new Date());}
function distance(m:number){return m>=1000?`${(m/1000).toFixed(1)}km`:`${Math.round(m)}m`;}function duration(s:number){const minutes=Math.round(s/60),hours=Math.floor(minutes/60);return hours?`${hours}小时${minutes%60?`${minutes%60}分钟`:""}`:`${minutes}分钟`;}function formatTolls(value:number){return Number.isInteger(value)?String(value):value.toFixed(1);}
function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,color:string){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=color;ctx.fill();}function canvasBlob(canvas:HTMLCanvasElement){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("长图生成失败")),"image/png"));}
async function loadImage(url:string):Promise<CanvasImageSource>{const response=await fetch(url,{cache:"no-store"});if(!response.ok||!(response.headers.get("content-type")||"").startsWith("image/"))throw new Error("静态地图请求失败");const blob=await response.blob();if("createImageBitmap" in window)return createImageBitmap(blob);return new Promise((resolve,reject)=>{const image=new Image(),objectUrl=URL.createObjectURL(blob);image.onload=()=>{URL.revokeObjectURL(objectUrl);resolve(image);};image.onerror=()=>{URL.revokeObjectURL(objectUrl);reject(new Error("静态地图加载失败"));};image.src=objectUrl;});}
function html(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));}function xml(v:string){return html(v);}
