import type { Day, Edge, Poi, ProjectListItem, ScheduleItem } from "../types";
import { createEmptyRoadbook, exportLocalRoadbook, getLocalRoadbook, hasImportSnapshot, importAsNewRoadbook, listLocalRoadbooks, mutateLocalRoadbook, replaceLocalRoadbook, undoLastImport } from "./local-roadbooks";

export const loadProjects = listLocalRoadbooks;
export const loadMobileData = (_userId: string, projectId: string) => getLocalRoadbook(projectId);
export const localProjectFiles = { createEmpty: createEmptyRoadbook, importNew: importAsNewRoadbook, replace: replaceLocalRoadbook, undo: undoLastImport, canUndo: hasImportSnapshot, export: exportLocalRoadbook };

export const mobilePoiApi = {
  create: (_userId: string, projectId: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const now = stamp(); const poi: Poi = { id: uid(), name: String(data.name || "未命名地点"), lng: Number(data.lng), lat: Number(data.lat), address: String(data.address || ""), tag: validTag(data.tag), amapPoiId: typeof data.amapPoiId === "string" ? data.amapPoiId : undefined, phone: String(data.phone || ""), notes: String(data.notes || ""), createdAt: now, updatedAt: now } as Poi; book.pois.push(poi); return clone(poi); }),
  update: (_userId: string, projectId: string, id: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const poi = required(book.pois.find((item) => item.id === id), "POI 不存在"); Object.assign(poi, data, { id, updatedAt: stamp() }); return clone(poi); }),
  delete: (_userId: string, projectId: string, id: string) => mutateLocalRoadbook(projectId, (book) => { const removedEdges = new Set(book.edges.filter((edge) => edge.originId === id || edge.destinationId === id).map((edge) => edge.id)); book.pois = book.pois.filter((poi) => poi.id !== id); book.edges = book.edges.filter((edge) => !removedEdges.has(edge.id)); book.days.forEach((day) => { day.items = day.items.filter((item) => item.poiId !== id).map((item, order) => ({ ...item, order, fromEdgeId: item.fromEdgeId && !removedEdges.has(item.fromEdgeId) ? item.fromEdgeId : null })); if (day.accommodationId === id) day.accommodationId = null; }); return { success: true }; }),
};

export const mobileEdgeApi = {
  create: (_userId: string, projectId: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const now = stamp(); const edge: Edge = { id: uid(), originId: String(data.originId), destinationId: String(data.destinationId), transportMode: String(data.transportMode || "driving"), drivingRoutes: cloneArray(data.drivingRoutes), cyclingRoutes: cloneArray(data.cyclingRoutes), walkingRoutes: cloneArray(data.walkingRoutes), customRoute: data.customRoute && typeof data.customRoute === "object" ? clone(data.customRoute) : null, selectedRouteIndex: Number(data.selectedRouteIndex) || 0, createdAt: now, updatedAt: now } as Edge; if (!book.pois.some((poi) => poi.id === edge.originId) || !book.pois.some((poi) => poi.id === edge.destinationId)) throw new Error("路线端点不存在"); book.edges.push(edge); return clone(edge); }),
  update: (_userId: string, projectId: string, id: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const edge = required(book.edges.find((item) => item.id === id), "路线不存在"); Object.assign(edge, data, { id, updatedAt: stamp() }); return clone(edge); }),
  delete: (_userId: string, projectId: string, id: string) => mutateLocalRoadbook(projectId, (book) => { book.edges = book.edges.filter((edge) => edge.id !== id); book.days.forEach((day) => day.items.forEach((item) => { if (item.fromEdgeId === id) item.fromEdgeId = null; })); return { success: true }; }),
};

export const mobileDayApi = {
  create: (_userId: string, projectId: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const position = clamp(Math.trunc(Number(data.insertAt)) || book.days.length + 1, 1, book.days.length + 1); book.days.sort(daySort).splice(position - 1, 0, newDay(projectId, position, data)); renumberDays(book.days); return clone(book.days[position - 1]); }),
  update: (_userId: string, projectId: string, id: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const day = required(book.days.find((item) => item.id === id), "日程不存在"); Object.assign(day, data, { id, updatedAt: stamp() }); return clone(day); }),
  delete: (_userId: string, projectId: string, id: string) => mutateLocalRoadbook(projectId, (book) => { book.days = book.days.filter((day) => day.id !== id); renumberDays(book.days); return { success: true }; }),
  reorder: (_userId: string, projectId: string, dayIds: string[]) => mutateLocalRoadbook(projectId, (book) => { if (dayIds.length !== book.days.length || new Set(dayIds).size !== dayIds.length) throw new Error("日程顺序不完整"); const byId = new Map(book.days.map((day) => [day.id, day])); book.days = dayIds.map((id) => required(byId.get(id), "日程顺序包含未知项目")); renumberDays(book.days); return clone(book.days); }),
  reverse: (_userId: string, projectId: string) => mutateLocalRoadbook(projectId, (book) => { book.days.sort(daySort).reverse(); for (const day of book.days) reverseDay(day, book.edges); renumberDays(book.days); return clone(book.days); }),
};

export const mobileScheduleApi = {
  insertAt: (_userId: string, projectId: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const day = required(book.days.find((item) => item.id === data.dayId), "日程不存在"); const position = clamp(Math.trunc(Number(data.insertAt)) || 0, 0, day.items.length); const item: ScheduleItem = { id: uid(), dayId: day.id, poiId: String(data.poiId), order: position, arrivalTime: typeof data.arrivalTime === "string" ? data.arrivalTime : null, departureTime: typeof data.departureTime === "string" ? data.departureTime : null, stayDuration: data.stayDuration && typeof data.stayDuration === "object" ? clone(data.stayDuration) as ScheduleItem["stayDuration"] : { hours: 0, minutes: 0 }, fromEdgeId: typeof data.fromEdgeId === "string" ? data.fromEdgeId : null, notes: String(data.notes || "") }; day.items.sort(itemSort).splice(position, 0, item); renumberItems(day); return clone(day); }),
  update: (_userId: string, projectId: string, id: string, data: Record<string, unknown>) => mutateLocalRoadbook(projectId, (book) => { const item = required(book.days.flatMap((day) => day.items).find((entry) => entry.id === id), "日程项目不存在"); Object.assign(item, data, { id }); return { success: true }; }),
  delete: (_userId: string, projectId: string, id: string) => mutateLocalRoadbook(projectId, (book) => { for (const day of book.days) { const before = day.items.length; day.items = day.items.filter((item) => item.id !== id); if (day.items.length !== before) renumberItems(day); } return { success: true }; }),
  reorder: (_userId: string, projectId: string, dayId: string, itemIds: string[]) => mutateLocalRoadbook(projectId, (book) => { const day = required(book.days.find((item) => item.id === dayId), "日程不存在"); if (itemIds.length !== day.items.length || new Set(itemIds).size !== itemIds.length) throw new Error("POI 顺序不完整"); const byId = new Map(day.items.map((item) => [item.id, item])); day.items = itemIds.map((id) => required(byId.get(id), "POI 顺序包含未知项目")); renumberItems(day); return clone(day); }),
};

export const mobileProjectApi = {
  rename: (_userId: string, projectId: string, name: string) => mutateLocalRoadbook(projectId, (book) => { book.metadata.name = name; return { success: true }; }),
};

function reverseDay(day: Day, edges: Edge[]): void { const original = [...day.items].sort(itemSort); day.items = [...original].reverse().map((item, order) => ({ ...item, order, fromEdgeId: null })); for (let index = 1; index < day.items.length; index++) { const from = day.items[index - 1].poiId, to = day.items[index].poiId; const old = original.find((entry, oldIndex) => oldIndex > 0 && entry.poiId === from && original[oldIndex - 1]?.poiId === to)?.fromEdgeId || null; day.items[index].fromEdgeId = reverseEdgeId(old, edges); } }
function reverseEdgeId(id: string | null, edges: Edge[]): string | null { if (!id) return null; const edge = edges.find((item) => item.id === id); if (!edge) return null; const existing = edges.find((item) => item.originId === edge.destinationId && item.destinationId === edge.originId && item.transportMode === edge.transportMode); if (existing) return existing.id; const reversed = { ...clone(edge), id: uid(), originId: edge.destinationId, destinationId: edge.originId, drivingRoutes: reverseRoutes(edge.drivingRoutes), cyclingRoutes: reverseRoutes(edge.cyclingRoutes), walkingRoutes: reverseRoutes(edge.walkingRoutes), customRoute: edge.customRoute ? { ...clone(edge.customRoute), polyline: [...edge.customRoute.polyline].reverse() } : null, createdAt: stamp(), updatedAt: stamp() }; edges.push(reversed); return reversed.id; }
function reverseRoutes(routes: Edge["drivingRoutes"]): Edge["drivingRoutes"] { return routes.map((route) => ({ ...clone(route), polyline: [...route.polyline].reverse() })); }
function newDay(projectId: string, position: number, data: Record<string, unknown>): Day { const now = stamp(); return { id: uid(), projectId, dayNumber: position, date: typeof data.date === "string" ? data.date : null, label: typeof data.label === "string" ? data.label : null, accommodationId: typeof data.accommodationId === "string" ? data.accommodationId : null, items: [], notesContent: String(data.notesContent || ""), notesMentions: cloneArray(data.notesMentions).filter((item): item is string => typeof item === "string"), createdAt: now, updatedAt: now } as Day; }
function renumberDays(days: Day[]): void { days.forEach((day, index) => { day.dayNumber = index + 1; day.updatedAt = stamp(); }); }
function renumberItems(day: Day): void { day.items.forEach((item, index) => { item.order = index; item.dayId = day.id; }); day.updatedAt = stamp(); }
function validTag(value: unknown): Poi["tag"] { return ["normal","hotel","restaurant","gas_station"].includes(String(value)) ? value as Poi["tag"] : "normal"; }
function required<T>(value: T | undefined, message: string): T { if (value === undefined) throw new Error(message); return value; }
function cloneArray(value: unknown): any[] { return Array.isArray(value) ? clone(value) : []; }
function clone<T>(value: T): T { return structuredClone(value); }
function uid(): string { return crypto.randomUUID(); }
function stamp(): string { return new Date().toISOString(); }
function clamp(value: number, min: number, max: number): number { return Math.min(max, Math.max(min, value)); }
function daySort(a: Day, b: Day): number { return a.dayNumber - b.dayNumber; }
function itemSort(a: ScheduleItem, b: ScheduleItem): number { return a.order - b.order; }
